site_name: NAIS Handbook
repo_url: https://github.com/nais/handbook
site_url: https://handbook.nais.io/
theme:
  name: material
  language: 'en'
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: slate
    primary: teal
    accent: green
  features:
    - content.code.annotate
    - navigation.instant
extra:
  generator: false
  search:
    language: 'en'
extra_javascript:
  - amplitude_javascript/events.js
plugins:
  - search
markdown_extensions:
  - toc:
      permalink: True
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.superfences:
        preserve_tabs: true
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.tasklist
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - tables
