name: Test Poetry build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: git-checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version-file: '.python-version'
      - name: Install all dependencies
        run: |
          pip install poetry==1.1.14
          poetry install
      - name: Build
        run: poetry run mkdocs build
